basePath: /
definitions:
  apiresp.ApiResponse:
    properties:
      data: {}
      errCode:
        type: integer
      errDlt:
        type: string
      errMsg:
        type: string
    type: object
  msg.ActiveUser:
    properties:
      count:
        type: integer
      user:
        $ref: '#/definitions/sdkws.UserInfo'
    type: object
  msg.GetActiveUserResp:
    properties:
      dateCount:
        additionalProperties:
          type: integer
        type: object
      msgCount:
        type: integer
      userCount:
        type: integer
      users:
        items:
          $ref: '#/definitions/msg.ActiveUser'
        type: array
    type: object
  sdkws.UserInfo:
    properties:
      appMangerLevel:
        type: integer
      createTime:
        type: integer
      ex:
        type: string
      faceURL:
        type: string
      globalRecvMsgOpt:
        type: integer
      nickname:
        type: string
      userID:
        type: string
    type: object
  user.UserRegisterCountResp:
    properties:
      before:
        type: integer
      count:
        additionalProperties:
          type: integer
        type: object
      total:
        type: integer
    type: object
host: localhost:10002
info:
  contact:
    email: ilovecoding@foxmail.com
    name: 飞宏IM技术支持
    url: https://github.com/liony823/chat
  description: 飞宏IM接口
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: 飞宏IM接口
  version: 1.0.0
paths:
  /statistics/user/active:
    post:
      consumes:
      - application/json
      description: 获取活跃用户
      operationId: GetActiveUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apiresp.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/msg.GetActiveUserResp'
              type: object
      summary: 获取活跃用户
      tags:
      - statistics
  /statistics/user/register:
    post:
      consumes:
      - application/json
      description: 获取注册用户数
      operationId: UserRegisterCount
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apiresp.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/user.UserRegisterCountResp'
              type: object
      summary: 获取注册用户数
      tags:
      - statistics
securityDefinitions:
  BearerAuth:
    description: '"Type ''Bearer'' followed by a space and JWT token"'
    in: header
    name: token
    type: apiKey
swagger: "2.0"
